config/routes.rb
Rails.application.routes.draw do
  resources :ports
  resources :pricing_matrices
  resources :inquiries
  resources :applications do
    member do
      get :download_pdf
      get :document  # Serves PDF inline for viewing
    end
  end
  resources :quotes
  devise_for :users

  resources :events do
    resources :images, only: [:create, :destroy]
  end


  get 'dashboard', to: 'dashboard#index', as: 'admin_dashboard'
  post 'dashboard/mass_message', to: 'dashboard#mass_message', as: 'mass_message_admin'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :employees, controller: 'employees'
  
  resources :bids do
    collection do
      post :upload_csv
      get  :download_processed
    end
  end

  # Defines the root path route ("/")
  
  root to: "home#index"

  get '*path', to: redirect('/')
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :set_employee, only: [:show, :edit, :update]
  after_action :verify_authorized

    def index
        @employees = User.all
        authorize User
    end

    def show
        render :show
        authorize @employee
    end

    def edit
        authorize @employee
    end

    def update
        if @employee.update(employee_params)
          redirect_to employee_path(@employee), notice: 'Employee was successfully updated.'
        else
          render :edit
        end
        authorize @employee
    end


    private

    def employee_params
        params.require(:user).permit(:name, :email, :role)
    end

    def set_employee
        @employee = User.find(params[:id])
    end
end

app/views/employees/_employee.html.erb
<div class="card">
    <div class="card-body">
        <h6 class="card-subtitle mb-2 text-muted"><%= @employee&.role %></h6>
        <p class="card-text">Email: <%= @employee&.email %></p>
    </div>
</div>

app/views/employees/edit.html.erb
<div class="container">
    <h1>Edit Employee</h1>

   <%= form_with(model: @employee, url: employee_path(@employee), method: :patch, local: true, class: "form") do |f| %>
        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
        </div>


        <div class="form-group">
            <%= f.label :role %>
            <%= f.select :role, options_for_select(["user", "admin", "hiring", "broker"], @employee.role), class: "form-control" %>
        </div>

        <div class="form-group">
            <%= f.submit "Update Employee", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row justify-content-between align-items-center">
  <div class="col-auto d-flex align-items-center">
    <h2 class="me-2">Employees</h2>
    <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#helpModalEmployees" title="Help & Instructions">
      <i class="fas fa-question-circle"></i>
    </button>
  </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @employees.each do |employee| %>
            <tr>
                <td><%= employee&.name %></td>
                <td><%= employee&.email %></td>
                <td><%= employee&.role %></td>
                <td>
                    <%= link_to 'Edit Employee', employee_path(employee), class: 'btn btn-info' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<!-- Help Modal -->
<%= render 'shared/help_modal', page_name: 'employees', page_title: 'Employee Management' %>

app/views/employees/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h1>Employee Details</h1>
            <div class="card">
                <%= render 'employees/employee' %>
            </div>
            <%= link_to "Change Privileges", edit_employee_path(@employee), class: "btn btn-primary" %>
        </div>
    </div>
</div>